### ISSUE TITLE
Using Class & ID selectors 

### ISSUE THREAD

**Issue by zannain** [krtong/prj-rev-bwfs-dasmoto#3]
I recommend against using to many element selectors to apply your CSS styles. Element selectors are some of the more broad CSS selectors available and a better alternative is to use a `class` or `id`. Since you only select `<h2>` once in your style sheets, rather using an [`h2` selector](https://github.com/krtong/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/Resources/CSS/style.css#L12-L15) and `id` would be more appropriate because it is more concise and you can give it a name that accurately reflects what is being styled.

```css
/* Not recommended */
.item h2 {
  color: white;
  font-size: 32px;
}

/* Recommended */
#item {
  color: white;
  font-size: 32px;
}
```
